name: Deploy Python project to Azure Function App

on:
  workflow_call:
    inputs:
      azure-functionapp-name:
        description: "Name of the Azure Function"
        required: true
        type: string
      azure-functionapp-package-path:
        description: "Path to function app project; defaults to the repository root"
        required: false
        type: string
        default: "."
      python-version:
        required: true
        type: string

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python ${{ inputs.python-version }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Dependencies
      run: |
        pushd './${{ inputs.azure-functionapp-package-path }}'
        python -m pip install --upgrade pip
        python -m pip install poetry && \
        poetry install
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ inputs.azure-functionapp-name }}
        package: ${{ inputs.azure-functionapp-package-path }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true